### ISSUE TITLE
Keep track of client and server versions, and warn client if they're not in sync

### ISSUE THREAD

**Issue by CSchank** [CSchank/petri-app-land#65]
Each time the client and server are regenerated, the version number may be bumped. 

# Versioning format proposal
The version format will be in the format "appid-vx.y" where `x` and `y` are numbers from 0 to infinity. 
- The `appid` is a randomly generated, 8-character hash when the project is first generated. This ensures you can't try to connect to a server for another app by accident.
- The `x` number is the major version. A client and server must be of the same major version in order to communicate. Otherwise, an error will be shown.
- The `y` number is the minor version. A client and server with different minor versions can still communicate.
- When the major version is bumped, the minor version is reset to 0.

## Proposal for determining version bumps
Version bumps will be calculated whenever the apps is regenerated from the specification. The following rules will be used to determine version bumps:

### Major versions
Major versions involve changes in how the server and client communicate. The following will cause changes in the major version:
- Adding a new Transition (either `Transition` or `CmdTransition`)
- Modifying the data sent with a transition (either `Transition` or `CmdTransition`) with origin `OriginClientOnly` or `OriginBothPossible`
- Modifying the connection list of an existing transition
- Renaming a place or transition
- Deleting a Transition (either `Transition` or `CmdTransition`) with a connection list longer than 0, that is not `OriginServerOnly`.
- Adding a new place
- Removing a place

### Minor versions
Major versions involve changes local to the client or server. The following will cause changes in the major version:
- Adding a new ClientTransition
- Modifying the data sent with a transition (either `Transition` or `CmdTransition`) with origin `OriginServerOnly`
- Changing the data of an existing place

## Heuristic for now
This is probably more complicated than what we need for now, and would require us to save more metadata between version, in addition to the generated code, so for now we will use the following heuristics to determine if a major/minor bump is needed. These should catch most, if not all, of the above criteria.

### Major version
Bump the major version on the client and server if any part of the Decode or Encode modules for the client or server are modified.

### Minor version
Any time any files (except for the `Encode` and `Decode` modules) are regenerated on the client or server, bump the minor version on both the client and server.

@Necried and @dandoh, thoughts?

**Comment by CSchank** [comment]
If a version is wrong, the client will show an error and will not be able to connect to the server.

**Comment by Necried** [comment]
Seems good, but one problem I see is that during development, someone might update the spec a lot, and when it's finally ready for deployment, the version number might be really big. Shouldn't be really an issue though, if we're not showing these version numbers to end-users?

**Comment by CSchank** [comment]
What if we gave a three-version format, x.y.z, where x gets incremented by a "draft release" type option? The creator can choose it when they want to, which would reset the y and z and just increment the x by one.

**Comment by christopheranand** [comment]
I think this versioning strategy is based on the versioning of libraries, where major and minor versions make sense, and is not the best approach for us.  When we can independently publish subnets, they will need this kind of versioning, but for the server<->client versioning, it would be better to just use unix time - 2019, for the time when the code generator runs.  Since the chance of two apps being generated at the same microsecond is 0%, this handles both versions and different apps, and forces the interfaces and transitions to match.  We don't even care if different versions of ghc and libraries are used or different versions of Elm packages, as far as the server<->client connection goes.
If we ever fix a bug and want to force all components to be at that version or greater, we just need to do the generation again.  This requires that the version (unixTime-2019) must overwrite the old one.  This would be easy to do if there is one .elm and one .hs with the version defined which are always overwritten.

**Comment by CSchank** [comment]
@christopheranand Yes that idea sounds like it should be easy and fine for now, but my reasoning to do something smarter was so that if only client transitions were edited for example, you wouldn't need to rebuild or even restart the server to make changes to the client. However, it would be quite complicated so I think for now that is fine.

I suppose we can include a makefile to build both the client and the server, which would reduce the amount of directory changing and commands that need to be written.
