### ISSUE TITLE
Generate GET, UPDATE, ALTER for every type with single data constructor

### ISSUE THREAD

**Issue by dandoh** [CSchank/petri-app-land#75]

**Comment by CSchank** [comment]
Implemented in 5f29eb12ef9f526b18dfb2b728595aace0265362. @dandoh please test this and close this issue if you're satisfied that it works properly. We only generate them for singleton types currently due to the added complexity of considering multiple constructors, but this should cover most of our use cases anyway.

**Comment by CSchank** [comment]
Appears to work, so we'll close. Reopen if you find any bugs.
